# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcase', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='medium',
            options={'verbose_name_plural': 'media'},
        ),
        migrations.AlterField(
            model_name='work',
            name='size_unit',
            field=models.CharField(choices=[('cm', 'centimeters'), ('in', 'inches')], default='in', max_length=2),
        ),
    ]
