PUBLIC_CHOICES = ((True, 'Public'), (False, 'Private'))

LANGUAGES = (
    # ISO 639-2 Language codes, as per LoC,
    # filtered for broad Soviet relevancy
    # http://www.loc.gov/standards/iso639-2/php/code_list.php
    ('abk', 'Abkhazian'),
    ('alb', 'Albanian'),
    ('ara', 'Arabic'),
    ('arm', 'Armenian'),
    ('ava', 'Avaric'),
    ('aze', 'Azerbaijani'),
    ('bak', 'Bashkir'),
    ('bel', 'Belarusian'),
    ('bos', 'Bosnian'),
    ('bul', 'Bulgarian'),
    ('bua', 'Buriat'),
    ('che', 'Chechen'),
    ('chi', 'Chinese'),
    ('chk', 'Chukchi'),
    ('chv', 'Chuvash'),
    ('crh', 'Crimean Tatar'),
    ('hrv', 'Croatian'),
    ('cze', 'Czech'),
    ('dar', 'Dargwa'),
    ('eng', 'English'),
    ('myv', 'Erzya'),
    ('est', 'Estonian'),
    ('fin', 'Finnish'),
    ('fre', 'French'),
    ('ger', 'German'),
    ('gre', 'Greek'),
    ('hin', 'Hindi'),
    ('hun', 'Hungarian'),
    ('inh', 'Ingush'),
    ('ita', 'Italian'),
    ('jpn', 'Japanese'),
    ('xal', 'Kalmyk'),
    ('krc', 'Karachay-Balkar'),
    ('kaa', 'Karakalpak'),
    ('kaz', 'Kazakh'),
    ('kom', 'Komi'),
    ('kor', 'Korean'),
    ('kum', 'Kumyk'),
    ('kir', 'Kyrgyz'),
    ('lat', 'Latvian'),
    ('lez', 'Lezgian'),
    ('lit', 'Lithuanian'),
    ('mac', 'Macedonian'),
    ('chm', 'Mari'),
    ('mdf', 'Moksha'),
    ('nog', 'Nogai'),
    ('oss', 'Ossetic'),
    ('pol', 'Polish'),
    ('por', 'Portuguese'),
    ('pan', 'Punjabi'),
    ('rum', 'Romanain'),
    ('rus', 'Russian'),
    ('srp', 'Serbian'),
    ('slo', 'Slovakian'),
    ('slv', 'Slovenian'),
    ('spa', 'Spanish'),
    ('tgk', 'Tajik'),
    ('tat', 'Tatar'),
    ('tuk', 'Turkmen'),
    ('udm', 'Udmurt'),
    ('ukr', 'Ukrainian'),
    ('uzb', 'Uzbek'),
    ('sah', 'Yakut'),
)
