# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 16:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcase.Category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name_first', models.CharField(max_length=50)),
                ('name_last', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(height_field='image_h', upload_to='', width_field='image_w')),
                ('image_h', models.IntegerField()),
                ('image_w', models.IntegerField()),
                ('aspect', models.CharField(choices=[('recto', 'recto'), ('verso', 'verso'), ('detail', 'detail'), ('signature', 'signature')], max_length=10)),
                ('caption', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('sublocation', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('value_currency', models.CharField(choices=[('usd', 'US Dollar'), ('eur', 'Euro'), ('gbp', 'British Pound')], default='usd', max_length=3)),
                ('value_type', models.CharField(choices=[('fmv', 'fair market value'), ('rpv', 'replacement value')], default='fmv', max_length=3)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('sku', models.CharField(max_length=100)),
                ('size_h', models.DecimalField(decimal_places=3, max_digits=6)),
                ('size_w', models.DecimalField(decimal_places=3, max_digits=6)),
                ('size_d', models.DecimalField(decimal_places=3, max_digits=6)),
                ('size_unit', models.CharField(choices=[('cm', 'centimeters'), ('in', 'inches')], max_length=2)),
                ('condition', models.CharField(choices=[('loss', 'total loss'), ('poor', 'poor'), ('fair', 'fair'), ('good', 'good'), ('very_good', 'very good'), ('excellent', 'excellent')], max_length=10)),
                ('status', models.CharField(choices=[('?', 'missing'), ('display', 'on display'), ('storage', 'in storage')], max_length=10)),
                ('notes', models.TextField()),
                ('categories', models.ManyToManyField(to='artcase.Category')),
                ('collections', models.ManyToManyField(to='artcase.Collection')),
                ('creators', models.ManyToManyField(to='artcase.Creator')),
                ('exhibits', models.ManyToManyField(to='artcase.Exhibit')),
                ('images', models.ManyToManyField(to='artcase.Image')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcase.Location')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artcase.Medium')),
                ('subjects', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('values', models.ManyToManyField(to='artcase.Value')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
