# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artcase', '0002_auto_20161001_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='exhibits',
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artcase.Category'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='creator',
            name='name_first',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='image',
            name='aspect',
            field=models.CharField(blank=True, choices=[('recto', 'recto'), ('verso', 'verso'), ('detail', 'detail'), ('signature', 'signature')], max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='caption',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='sublocation',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(blank=True, to='artcase.Category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='collections',
            field=models.ManyToManyField(blank=True, to='artcase.Collection'),
        ),
        migrations.AlterField(
            model_name='work',
            name='condition',
            field=models.CharField(blank=True, choices=[('loss', 'total loss'), ('poor', 'poor'), ('fair', 'fair'), ('good', 'good'), ('vgood', 'very good'), ('excel', 'excellent')], max_length=5),
        ),
        migrations.AlterField(
            model_name='work',
            name='creators',
            field=models.ManyToManyField(blank=True, to='artcase.Creator'),
        ),
        migrations.AlterField(
            model_name='work',
            name='images',
            field=models.ManyToManyField(blank=True, to='artcase.Image'),
        ),
        migrations.AlterField(
            model_name='work',
            name='location',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artcase.Location'),
        ),
        migrations.AlterField(
            model_name='work',
            name='medium',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='artcase.Medium'),
        ),
        migrations.AlterField(
            model_name='work',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='size_d',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='work',
            name='size_h',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='work',
            name='size_w',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='work',
            name='status',
            field=models.CharField(blank=True, choices=[('?', 'missing'), ('display', 'on display'), ('storage', 'in storage')], max_length=10),
        ),
        migrations.AlterField(
            model_name='work',
            name='values',
            field=models.ManyToManyField(blank=True, to='artcase.Value'),
        ),
        migrations.DeleteModel(
            name='Exhibit',
        ),
    ]
