# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 12:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcase', '0004_auto_20161019_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artcase.Category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='artcase.Category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, to='artcase.Collection'),
        ),
        migrations.AlterField(
            model_name='work',
            name='creators',
            field=models.ManyToManyField(blank=True, null=True, to='artcase.Creator'),
        ),
        migrations.AlterField(
            model_name='work',
            name='images',
            field=models.ManyToManyField(blank=True, null=True, to='artcase.Image'),
        ),
        migrations.AlterField(
            model_name='work',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artcase.Location'),
        ),
        migrations.AlterField(
            model_name='work',
            name='medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artcase.Medium'),
        ),
        migrations.AlterField(
            model_name='work',
            name='size_unit',
            field=models.CharField(choices=[('cm', 'centimeters'), ('in', 'inches')], default='in', max_length=2),
        ),
        migrations.AlterField(
            model_name='work',
            name='values',
            field=models.ManyToManyField(blank=True, null=True, to='artcase.Value'),
        ),
    ]
