# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcase', '0005_auto_20161019_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='categories',
            field=models.ManyToManyField(blank=True, to='artcase.Category'),
        ),
        migrations.AlterField(
            model_name='work',
            name='collections',
            field=models.ManyToManyField(blank=True, to='artcase.Collection'),
        ),
        migrations.AlterField(
            model_name='work',
            name='creators',
            field=models.ManyToManyField(blank=True, to='artcase.Creator'),
        ),
        migrations.AlterField(
            model_name='work',
            name='images',
            field=models.ManyToManyField(blank=True, to='artcase.Image'),
        ),
        migrations.AlterField(
            model_name='work',
            name='values',
            field=models.ManyToManyField(blank=True, to='artcase.Value'),
        ),
    ]
