# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcase', '0006_auto_20161019_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='sku',
            field=models.SlugField(max_length=100),
        ),
    ]
