# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artcase', '0010_auto_20161022_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='sublocation',
        ),
        migrations.AlterField(
            model_name='value',
            name='value_type',
            field=models.CharField(choices=[('fmv', 'fair market'), ('rpv', 'replacement')], default='fmv', max_length=3),
        ),
    ]
