# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-17 02:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artcase', '0011_auto_20161110_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
